from src.config.settings import (
    # Instances
    api_config,
    request_config,
    crawler_config,
    path_config,
    logging_config,
    # Legacy-compatible constants
    USE_SEMANTIC_SCHOLAR_API_KEYS,
    SEMANTIC_SCHOLAR_API_KEY,
    SEMANTIC_SCHOLAR_API_URL,
    OPENALEX_API_URL,
    REQUEST_TIMEOUT,
    MAX_RETRIES,
    RETRY_BACKOFF_FACTOR,
    SEMANTIC_SCHOLAR_RATE_LIMIT,
    OPENALEX_RATE_LIMIT,
    MAX_WORKERS,
    USE_CACHING,
    ENABLE_PROGRESS_BAR,
    SKIP_SECTIONS,
    DEFAULT_OUTPUT_DIR,
    BASE_CRAWLER_OUTPUT_DIR,
    EXTENDED_CRAWLER_OUTPUT_DIR,
    CITATIONS_CRAWLER_OUTPUT_DIR,
    LOG_FILE,
    LOG_LEVEL,
    LOG_FORMAT,
)